### ISSUE TITLE
XIV Meteor icon as the Galaxy "source" icon

### ISSUE THREAD

**Issue by LiteMorgan** [RZetko/galaxy-integration-ffxiv#1]
Thanks for getting this integration for GOG, much appreciated.

Would be nice to get the Meteor symbol added in as a source icon if possible? Currently the only game I have appearing with a blank source.

Hopefully not too hard to integrate!

**Comment by RZetko** [comment]
I'll look into it but I think this is limitation of missing FFXIV platform icon on GOG's backend as I haven't seen any methods to set platform icon in GOG integration API. I'll update this issue when I get more info. Thanks for feedback

**Comment by LiteMorgan** [comment]
Ah that's fair enough, didn't realise that was integrated at their end! Good old SE, making a standalone launcher. 😁

**Comment by RZetko** [comment]
After some investigation I found out that platform icon + few other platform related things are handled on GOG's backend without me having any ability to change it. Thanks for filling out this issue. I'm closing it for now and if there's a update on this in future, I'll reopen it.
