### ISSUE TITLE
Plugin doesn't dynamically detect that a game was installed

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [RZetko/galaxy-integration-ffxiv#3]
Hey,

if i connect the plugin without having FFXIV previously installed and then install it through 'Install' in Galaxy Client then the plugin won't send information to Galaxy that the game status changed to Installed until the next client restart.

Similar thing happens if the game was uninstalled while plugin was running. The state won't be updated until user restarts the client.

I think it would be best to check the game installation status from time to time and report it using self.update_local_game_status() method.

Hope this helps.

**Comment by RZetko** [comment]
Thanks for bug report and giving me advice. I implemented periodic checking of game state and this issue should be fixed in v1.1.2. If you notice any problems, please let me know.
