### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [RZetko/galaxy-integration-ffxiv#6]
Hey,

we're planning on creating a fork/autoupdate system with selected plugins. This would allow us to create a list of curated and reviewed plugins which could be of use to GOG Galaxy people.

Of course you will be credited as the creator and developer of the plugin in the fork readme and possibly other places.

Before we do that we need to ask you to create a fog_release branch which would contain only your plugin code, manifest.json and a requirements.txt file (without 3rdparty directories). For Github releases, we will include whole directory where manifest.json is placed and build dependencies directly there. This is for easier code verification. Code for repo synchronization can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater

So in your case the branch could have an example structure of:

html/your-html-files.html
your-python-files.py
manifest.json
requirements.txt
README.md
LICENSE

just without the modules directory

**Comment by FriendsOfGalaxy** [comment]
We aren't currently supporting dependencies being kept in folder separate from source so we will have to prepare for that first or if you want to process this faster you could support dependencies in root.
so 
`from modules.galaxy.api.plugin import Plugin, create_and_run_plugin`
becomes
`from galaxy.api.plugin import Plugin, create_and_run_plugin`

**Comment by RZetko** [comment]
That would be lovely. I'll get to it as soon as I can (I've been busy lately), fix the other issue you mentioned and ping you/close the issue. Thank you very much for your helpful advice.

**Comment by FriendsOfGalaxy** [comment]
Hey @RZetko! You can just create **`.fog_config.json`** with content:
```json
{
    "dependencies_dir": "modules"
}
```

and this should work fine when https://github.com/FriendsOfGalaxy/galaxy-integrations-updater/pull/8/fil is merged.
